objects/Account.object
<CustomObject>
    <fields>
        <fullName>CustomerNumber__c</fullName>
        <label>Customer Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerStatus__c</fullName>
        <description>10/19/2005 - Eli - changed length to 10 to match source data from DCS.</description>
        <label>Customer Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>6</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>SalesRepName__c</fullName>
        <description>Description for this SalesRep Id, from CC115 on the UVX. Usually the same as Account Owner name, except for house accounts.</description>
        <label>Sales Rep Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipToName__c</fullName>
        <label>Ship To Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipToNumber__c</fullName>
        <label>Ship To</label>
        <length>3</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/Waypoints.cls
global with sharing class Waypoints {


    public String start{
    get{
        if(start == null){
    //get start querystring param
    start = ApexPages.currentPage().getParameters().get('start');
    }
    return start;
    }
    set;
    }
    // Allow the user to check off which accounts to use for routing
    public String nextUrl{
        get{
            if(nextUrl==null) {
                nextUrl='';
            }
            return nextUrl;
        }
        set;
    }
    
    public List<AccountWrapper> results {get;set;}
      
    public void findAccounts() {
        results = new List<AccountWrapper>();

        List<Account>accounts = (List<Account>)[SELECT id,RecordTypeId, ShipToNumber__c ,Name,
        ShippingStreet,ShippingCity,CustomerNumber__c,SalesRepName__c,ShippingState,
        BillingStreet, BillingState, BillingPostalCode, BillingCountry, BillingCity,ShippingPostalCode, 
        ShippingCountry, Owner.Name, ShipToName__c, CustomerStatus__c, Location__Longitude__s, Location__Latitude__s 
        FROM Account WHERE Owner.Name =: Userinfo.getName() AND ShippingCity <> '' ORDER BY DISTANCE(Location__c, GEOLOCATION(37.775,-122.418), 'mi')];
        
        for(Account a : accounts) {
            AccountWrapper accountWrapper = new AccountWrapper(a);
            results.add(accountWrapper);
        }
        System.debug('************* Results: ' + results.size());
    }   
   
    public void next() {
        List<Id> accountIdsForUrl = new List<Id>();

        for(AccountWrapper aw : results) {
            if(aw.isChecked) {
                accountIdsForUrl.add(aw.account.Id);
            }
        }
        
        if(accountIdsForUrl.size()<2) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,Label.Select_More_Accounts));
            return; 
        }
        
        nextUrl = Url.getSalesforceBaseUrl().toExternalForm();
        nextUrl += createNextUrl(accountIdsForUrl);
         
  }
   
    public PageReference cancel() {
        return new PageReference('/001/o');  
    } 

    private String createNextUrl(List<Id> accountIds) {
        String url = '/apex/FindDirections?';
        for(Id id : accountIds) {
            url+='&cid='+id; 
        }
        return url;
    }
    
    //wrapper class for shown accounts
    public class AccountWrapper {
        public Boolean isChecked{get;set;}
        public Account account{get; private set;}
        
        public AccountWrapper(Account account) {
            this.account = account;
            isChecked = false;
        }
    }   
}